name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'

      - run: dotnet tool restore &&
             ./build.sh -v $(dotnet nbgv get-version -v SemVer2)

      - uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: bin/nuget

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: nuget

      - run: dotnet nuget push bin/nuget/*.nupkg
               --api-key ${{ secrets.NUGET_API_KEY }}
               --source https://api.nuget.org/v3/index.json

      - uses: svenstaro/upload-release-action@1.0.1
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: bin/nuget/*.nupkg
