name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'

      - name: NuGet cache
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json') }}-${{ hashFiles('*.lock') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: ./build.sh

      - name: Upload nupkg
        uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: bin/nuget
